favicon: null
name: OLTC 2016
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5435102935880423
  brandStrength: 0.5794906318187714
  rhythmicContrast: 0.4676739128772169
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.1465884922072291
typography_spectrum: 0.907881727674976
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6290323
analytics:
  twitter: null
  google: null
  facebook: null
